---
pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success=Community-TC (pull_request)
      - base=master
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash

  - name: Automatic merge on approval for contributors
    conditions:
      - author!=@mozilla/sallt
      - status-success=Community-TC (pull_request)
      - base=master
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: squash
