version: 1
policy:
  pullRequests: public
tasks:
  $let:
    head_branch:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.ref}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.ref}
        else: ${event.release.target_commitish}

    head_rev:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.sha}
      else:
        $if: 'tasks_for == "github-push"'
        then: ${event.after}
        else: ${event.release.tag_name}

    repository:
      $if: 'tasks_for == "github-pull-request"'
      then: ${event.pull_request.head.repo.html_url}
      else: ${event.repository.html_url}
  in:
    - taskId: {$eval: as_slugid("bot_checks")}
      provisionerId: aws-provisioner-v1
      workerType: github-worker
      created: {$fromNow: ''}
      deadline: {$fromNow: '1 hour'}
      extra:
        github:
          events:
            - pull_request.opened
            - pull_request.reopened
            - pull_request.synchronize
            - push
      payload:
        maxRunTime: 3600
        image: python:3-alpine
        env:
          GIT_REPOSITORY: ${repository}
          GIT_REVISION: ${head_rev}
        command:
          - sh
          - -lxce
          - "apk add git --quiet &&
            git clone --quiet ${repository} /src && cd /src/bot && git checkout ${head_rev} -b checks &&
            pip install . && pip install -r requirements-dev.txt &&
            flake8 && pytest -v"
      metadata:
        name: Code Review Bot checks
        description: Check python code (unit tests & linting)
        owner: bastien@mozilla.com
        source: https://github.com/mozilla/code-review
