graph TD

push --> check_lint
push --> backend_check_tests
push --> frontend_build
push --> integration_check_tests
check_lint --> backend_build
backend_check_tests --> backend_build
check_lint --> integration_build
integration_check_tests --> integration_build

frontend_build --> frontend_deploy
backend_build --> backend_deploy
integration_build --> integration_deploy

subgraph deployment
  frontend_deploy
  backend_deploy
  integration_deploy
  integration_deploy --> integration_hook
end


backend_build --> github_release
frontend_build --> github_release
integration_build --> github_release

subgraph release
  github_release
end
