sequenceDiagram

  Phabricator->>+Web: GET /codereview/new
  Web->>+Redis: Store build reference X
  Worker->>Redis: Got any build ?
  Redis->>Worker: Here is build X
  Worker->>+Phabricator: Is build X publicly available ?
  Phabricator->>+Worker: No, it's still private
  Worker->>Worker: Let's wait a bit
  Worker->>+Phabricator: Is build X publicly available ?
  Phabricator->>+Worker: Yes.
  Worker->>+Phabricator: Give me the stack of X
  Phabricator->>+Worker: Here is a list of patches
  Worker->>Worker: Let's apply that stack on my local clone
  Worker->>Try: hg push -f try
  Try->>Worker: ok, it will be on treeherder as XYZ
  Worker->>Phabricator: Here is the treeherder link XYZ for build X
