# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 2.2.6 on 2019-10-31 09:46

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [("issues", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="diff",
            name="analyzers_group_id",
            field=models.CharField(max_length=30, null=True, unique=True),
        )
    ]
