# -*- coding: utf-8 -*-
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

# Generated by Django 4.0.5 on 2022-06-30 12:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0004_issue_in_patch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="check",
            new_name="analyzer_check",
        ),
    ]
