# -*- coding: utf-8 -*-
# Generated by Django 4.0.5 on 2022-06-30 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0004_issue_in_patch"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="check",
            new_name="analyzer_check",
        ),
    ]
