# Generated by Django 5.1 on 2024-09-10 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0010_alter_revision_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(fields=["path"], name="issues_issu_path_ee2627_idx"),
        ),
        migrations.AddIndex(
            model_name="revision",
            index=models.Index(
                fields=["head_repository", "head_changeset"],
                name="issues_revi_head_re_7be180_idx",
            ),
        ),
    ]
