# Generated by Django 5.1.1 on 2024-10-14 13:05

from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def move_attributes(apps, schema_editor):
    """
    Update values for new attributes on IssueLink
    using source data from linked Issue
    """
    IssueLink = apps.get_model("issues", "IssueLink")
    Issue = apps.get_model("issues", "Issue")

    IssueLink.objects.update(
        in_patch=Subquery(
            Issue.objects.filter(id=OuterRef("issue_id")).values("in_patch")[:1]
        ),
        new_for_revision=Subquery(
            Issue.objects.filter(id=OuterRef("issue_id")).values("new_for_revision")[:1]
        ),
    )


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0011_indexes_revision_issue_path"),
    ]

    operations = [
        # Create new fields on IssueLink
        migrations.AddField(
            model_name="issuelink",
            name="in_patch",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="new_for_revision",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="char",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="line",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="nb_lines",
            field=models.PositiveIntegerField(null=True),
        ),
        # Move all their values
        migrations.RunPython(move_attributes),
        # Remove old fields from Issue
        migrations.RemoveField(
            model_name="issue",
            name="in_patch",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="new_for_revision",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="char",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="line",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="nb_lines",
        ),
        # Update constraints
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_revision",
        ),
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_diff",
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("diff__isnull", True)),
                fields=("issue", "revision", "line", "nb_lines", "char"),
                name="issue_link_unique_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("diff__isnull", False)),
                fields=("issue", "revision", "diff", "line", "nb_lines", "char"),
                name="issue_link_unique_diff",
            ),
        ),
    ]
