# Generated by Django 5.1.1 on 2024-10-14 13:05

import tqdm
from django.db import migrations, models


def move_attributes(apps, schema_editor):
    """
    Update values for new attributes on IssueLink
    using source data from linked Issue
    """
    IssueLink = apps.get_model("issues", "IssueLink")

    links = IssueLink.objects.all().select_related("issue")
    for link in tqdm.tqdm(links.iterator(), total=links.count()):
        link.in_patch = link.issue.in_patch
        link.new_for_revision = link.issue.new_for_revision
        link.save()


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0011_indexes_revision_issue_path"),
    ]

    operations = [
        # Move in-patch & new_for_revision to IssueLink, propagating their state
        migrations.AddField(
            model_name="issuelink",
            name="in_patch",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="new_for_revision",
            field=models.BooleanField(null=True),
        ),
        migrations.RunPython(move_attributes),
        migrations.RemoveField(
            model_name="issue",
            name="in_patch",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="new_for_revision",
        ),
    ]
