# Generated by Django 5.1.1 on 2024-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0011_indexes_revision_issue_path"),
    ]

    operations = [
        # Create new fields on IssueLink
        migrations.AddField(
            model_name="issuelink",
            name="in_patch",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="new_for_revision",
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="char",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="line",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issuelink",
            name="nb_lines",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
