# Generated by Django 5.1.1 on 2024-10-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0012_move_issues_attributes_part_1"),
    ]

    operations = [
        # Move all their values
        migrations.RunSQL(
            """
            UPDATE issues_issuelink as link
            SET
                in_patch=i.in_patch,
                new_for_revision=i.new_for_revision,
                char=i.char,
                line=i.line,
                nb_lines=i.nb_lines
            FROM issues_issue as i
            WHERE i.id = link.issue_id
            """,
            reverse_sql="""
            UPDATE issues_issue as i
            SET
                in_patch=link.in_patch,
                new_for_revision=link.new_for_revision,
                char=link.char,
                line=link.line,
                nb_lines=link.nb_lines
            FROM issues_issuelink as link
            WHERE i.id = link.issue_id
            """,
        ),
        # Remove old fields from Issue
        migrations.RemoveField(
            model_name="issue",
            name="in_patch",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="new_for_revision",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="char",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="line",
        ),
        migrations.RemoveField(
            model_name="issue",
            name="nb_lines",
        ),
        # Update constraints
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_revision",
        ),
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_diff",
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("diff__isnull", True)),
                fields=("issue", "revision", "line", "nb_lines", "char"),
                name="issue_link_unique_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                condition=models.Q(("diff__isnull", False)),
                fields=("issue", "revision", "diff", "line", "nb_lines", "char"),
                name="issue_link_unique_diff",
            ),
        ),
    ]
