# Generated by Django 5.1.1 on 2024-11-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0014_unique_hash"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_revision",
        ),
        migrations.RemoveConstraint(
            model_name="issuelink",
            name="issue_link_unique_diff",
        ),
        migrations.AddConstraint(
            model_name="issuelink",
            constraint=models.UniqueConstraint(
                fields=("issue", "revision", "diff", "line", "nb_lines", "char"),
                name="issue_link_unique",
                nulls_distinct=False,
            ),
        ),
    ]
