# Generated by Django 5.1.2 on 2024-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0014_unique_hash"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="repository",
            name="phid",
        ),
        migrations.AlterField(
            model_name="repository",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
