# Generated by Django 5.1.6 on 2026-01-21 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0015_remove_repository_phid_alter_repository_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="revision",
            options={"ordering": ("provider", "provider_id", "id")},
        ),
        migrations.RemoveConstraint(
            model_name="revision",
            name="revision_unique_phab_id",
        ),
        migrations.RenameField(
            model_name="revision",
            old_name="phabricator_id",
            new_name="provider_id",
        ),
        migrations.AddField(
            model_name="revision",
            name="provider",
            field=models.CharField(
                choices=[("phabricator", "Phabricator"), ("github", "Github")],
                default="phabricator",
                max_length=20,
            ),
        ),
        migrations.AddConstraint(
            model_name="revision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_id__isnull", False)),
                fields=("provider_id",),
                name="revision_unique_phab_id",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="revision",
            name="revision_unique_phab_phabid",
        ),
        migrations.RemoveField(
            model_name="revision",
            name="phabricator_phid",
        ),
    ]
