# Generated by Django 5.1.6 on 2026-01-27 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0016_alter_revision_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="diff",
            old_name="phid",
            new_name="provider_id",
        ),
    ]
